package org.example;

public class JniCalculator implements Calculator {

  static {
    System.loadLibrary("native");
  }

  /*
   * Native C++ code that uses the org_example_JniCalculator.h header file generated by javac -h:
   *
   * JNIEXPORT jlong JNICALL Java_org_example_JniCalculator_add(JNIEnv *, jobject, jlong a, jlong b) {
   *     return a + b;
   * }
   */
  public native long add(final long a, final long b);

  public native long subtract(final long a, final long b);

  public native long multiply(final long a, final long b);

  public native long divide(final long a, final long b);
}
