/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_JniCalculator */

#ifndef _Included_org_example_JniCalculator
#define _Included_org_example_JniCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_JniCalculator
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_JniCalculator_add
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_example_JniCalculator
 * Method:    subtract
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_JniCalculator_subtract
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_example_JniCalculator
 * Method:    multiply
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_JniCalculator_multiply
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_example_JniCalculator
 * Method:    divide
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_example_JniCalculator_divide
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
